(define (make-account balance secret-password)
  (define n-login-attempts 0)
  (define (withdraw amount)
    (if (<= amount balance)
      (begin (set! balance (- balance amount)) balance)
      "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (call-the-cops) 
    (display "Calling the cops!"))
  (define (dispatch p m)
    (if (eq? p secret-password)
      (begin
	(set! n-login-attemps 0)
	(cond ((eq? m 'withdraw) withdraw)
	      ((eq? m 'deposit) deposit)
	      (else (error "Unknown request -- MAKE-ACCOUNT"
			   m))))
      (lambda (x)
	(set! n-login-attempts (+ n-login-attempts 1))
	(if (< n-login-attempts 7)
	  "Incorrect password"
	  (call-the-cops)))))
  dispatch)

(define acc (make-account 100 'secret-password))
((acc 'some-other-password 'deposit) 10)
((acc 'some-other-password 'deposit) 10)
((acc 'some-other-password 'deposit) 10)
((acc 'some-other-password 'deposit) 10)
((acc 'some-other-password 'deposit) 10)
((acc 'some-other-password 'deposit) 10)
((acc 'some-other-password 'deposit) 10)
