(define (make-account balance secret-password)
  (define (withdraw amount)
    (if (<= amount balance)
      (begin (set! balance (- balance amount)) balance)
      "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch p m)
    (if (eq? p secret-password)
      (cond ((eq? m 'withdraw) withdraw)
	    ((eq? m 'deposit) deposit)
	    (else (error "Unknown request -- MAKE-ACCOUNT"
			 m)))
      (lambda (x) "Incorrect password")))
  dispatch)

(define (make-joint acc secret-password joint-password)
  (define (dispatch p m)
    (if (eq? p joint-password)
      (acc secret-password m)
      (lambda (x) "Incorrect password")))
  dispatch)

(define peter-acc (make-account 100 'open-sesame))
(define paul-acc (make-joint peter-acc 'open-sesame 'rosebud))
((paul-acc 'rosebud 'withdraw) 50)
