(define (make-account balance secret-passwd)
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (withdraw amount)
    (cond ((>= balance amount)
	   (set! balance (- balance amount))
	   balance)
	  (else "Insufficient funds")))
  (define (dispatch passwd m)
    (cond 
      ((eq? passwd secret-passwd)
       (cond ((eq? m 'deposit) deposit)
	     ((eq? m 'withdraw) withdraw)
	     (else (error "Unknown request -- MAKE-ACCOUNT"
			  m))))
      (else (error "Incorrect password -- MAKE-ACCOUNT"))))
  dispatch)
